import { ArrowLeft, ArrowRight, Mail, ExternalLink, Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";
import SiteHeader, { getInitialTheme } from "./SiteHeader";
type Locale = "en" | "fa"; type Theme = "light" | "dark";
const copy = {
 en: { tag:"ONYX / CONTACT", kicker:"DIRECT CHANNEL", title:"START WITH THE OPERATION.", intro:"Tell us about the operational environment, continuity requirements, authority model, and deployment constraints you need ONYX to support.", email:"Email the ONYX team", emailAddress:"Soheil.Mozaffari@gmail.com", emailSubject:"ONYX enterprise enquiry", demoTitle:"Request a demonstration", demoBody:"A demonstration is most useful when it is grounded in a real operating scenario. Include your organization, operational context, connectivity conditions, deployment model, and the people or teams involved.", includeTitle:"Useful context to include", include:[["01","OPERATING ENVIRONMENT","Mission, field, infrastructure, emergency, government, or other operational context."],["02","CONNECTIVITY","Connected, degraded, intermittent, or routinely offline conditions."],["03","AUTHORITY","Roles, approval boundaries, delegation, and who is permitted to execute actions."],["04","DEPLOYMENT","Cloud, private infrastructure, edge, hybrid, or other deployment constraints."]], processTitle:"What happens next", process:[["01","CONTEXT","We review the operating scenario and constraints you provide."],["02","DISCUSSION","We establish the relevant ONYX product and architecture surfaces."],["03","DEMONSTRATION","Where appropriate, the conversation moves into a scenario-based product demonstration."]], fitTitle:"A useful first conversation", fitBody:"ONYX is designed for operations where continuity, authority, synchronization, evidence, and accountability need to remain explicit. The contact path is intended for substantive operational and enterprise enquiries rather than generic product feedback.", githubLabel:"Public engineering surface — GitHub repository", githubUrl:"https://github.com/SMozaff/Onyx-Framwork", about:"About ONYX", roadmap:"View roadmap", language:"فارسی", light:"Light mode", dark:"Dark mode", back:"Back to home" },
 fa: { tag:"ONYX / تماس", kicker:"کانال مستقیم", title:"از عملیات شروع کنید.", intro:"درباره محیط عملیاتی، نیازهای تداوم، مدل اختیار و محدودیت‌های استقرار موردنیاز برای ONYX توضیح دهید.", email:"ارسال ایمیل به تیم ONYX", emailAddress:"Soheil.Mozaffari@gmail.com", emailSubject:"درخواست سازمانی ONYX", demoTitle:"درخواست دمو", demoBody:"دمو زمانی بیشترین ارزش را دارد که بر یک سناریوی واقعی عملیاتی بنا شود. سازمان، زمینه عملیاتی، شرایط اتصال، مدل استقرار و افراد یا تیم‌های درگیر را توضیح دهید.", includeTitle:"اطلاعات مفید برای شروع", include:[["۰۱","محیط عملیاتی","زمینه مأموریت، میدان، زیرساخت، امداد، دولت یا سایر محیط‌های عملیاتی."],["۰۲","اتصال","شرایط متصل، ضعیف، متناوب یا معمولاً آفلاین."],["۰۳","اختیار","نقش‌ها، مرزهای تأیید، تفویض اختیار و افراد مجاز به اجرای اقدامات."],["۰۴","استقرار","محدودیت‌های استقرار ابری، زیرساخت خصوصی، لبه، ترکیبی یا سایر مدل‌ها."]], processTitle:"پس از تماس چه اتفاقی می‌افتد", process:[["۰۱","زمینه","سناریو و محدودیت‌های عملیاتی ارائه‌شده را بررسی می‌کنیم."],["۰۲","گفت‌وگو","سطوح مرتبط محصول و معماری ONYX را مشخص می‌کنیم."],["۰۳","دمو","در صورت مناسب بودن، گفت‌وگو به دمو سناریومحور محصول می‌رسد."]], fitTitle:"یک گفت‌وگوی اولیه مفید", fitBody:"ONYX برای عملیاتی طراحی شده است که در آن تداوم، اختیار، همگام‌سازی، شواهد و پاسخ‌گویی باید صریح باقی بمانند. این مسیر برای درخواست‌های جدی عملیاتی و سازمانی در نظر گرفته شده است، نه بازخورد عمومی محصول.", githubLabel:"سطح مهندسی عمومی — مخزن GitHub", githubUrl:"https://github.com/SMozaff/Onyx-Framwork", about:"درباره ONYX", roadmap:"مشاهده نقشه راه", language:"English", light:"حالت روشن", dark:"حالت تاریک", back:"بازگشت به خانه" }
} as const;
export default function ContactPage({locale}:{locale:Locale}) {
 const rtl=locale==="fa", c=copy[locale], [theme,setTheme]=useState<Theme>(getInitialTheme), href=(p:string)=>p?`/${locale}/${p}/`:`/${locale}/`;
 const Arrow=rtl?ArrowRight:ArrowLeft;
 useEffect(()=>{const s=window.localStorage.getItem("onyx-theme") as Theme|null; const p=window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"; const n=s==="dark"||s==="light"?s:p; setTheme(n); document.documentElement.dataset.theme=n;},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme; window.localStorage.setItem("onyx-theme",theme);},[theme]);
 const mail=`mailto:${c.emailAddress}?subject=${encodeURIComponent(c.emailSubject)}`;
 return <main className={`contact-page contact-page--${theme}`} dir={rtl?"rtl":"ltr"}>
 <SiteHeader locale={locale} theme={theme} onToggleTheme={() => setTheme((current) => current === "dark" ? "light" : "dark")} activePage="contact" />
 <section className="contact-hero"><div className="contact-grid" aria-hidden="true"/><div className="shell-content contact-hero__inner"><div className="contact-kicker"><span/>{c.tag}</div><p className="contact-eyebrow">{c.kicker}</p><h1>{c.title}</h1><p className="contact-intro">{c.intro}</p><a className="contact-primary" href={mail}><Mail size={17}/>{c.email}</a></div></section>
 <section className="contact-section contact-section--demo"><div className="shell-content contact-two-col"><div><span className="contact-label">01 / {rtl?"دمو":"DEMO"}</span><h2>{c.demoTitle}</h2></div><div><p className="contact-lead">{c.demoBody}</p><a className="contact-email" href={mail}>{c.emailAddress}<ExternalLink size={15}/></a></div></div></section>
 <section className="contact-section contact-section--context"><div className="shell-content"><div className="contact-heading"><span className="contact-label">02 / {rtl?"زمینه":"CONTEXT"}</span><h2>{c.includeTitle}</h2></div><div className="contact-context-grid">{c.include.map(([n,t,b])=><article key={n}><span>{n}</span><b>{t}</b><p>{b}</p></article>)}</div></div></section>
 <section className="contact-section contact-section--process"><div className="shell-content contact-two-col"><div><span className="contact-label">03 / {rtl?"فرآیند":"PROCESS"}</span><h2>{c.processTitle}</h2></div><div className="contact-process">{c.process.map(([n,t,b])=><article key={n}><span>{n}</span><div><b>{t}</b><p>{b}</p></div></article>)}</div></div></section>
 <section className="contact-section contact-section--fit"><div className="shell-content contact-two-col"><div><span className="contact-label">04 / {rtl?"تناسب":"FIT"}</span><h2>{c.fitTitle}</h2></div><div><p className="contact-lead">{c.fitBody}</p><a className="contact-email" href={c.githubUrl} target="_blank" rel="noreferrer">{c.githubLabel}<ExternalLink size={15}/></a></div></div></section>
 <footer className="contact-footer"><div className="shell-content contact-footer__inner"><a href={href("")}><Arrow size={15}/>{c.back}</a><span>ONYX / CONTACT</span></div></footer></main>;
}