import { ArrowLeft, ArrowRight, Check, ChevronRight, Moon, ShieldCheck, Sun } from "lucide-react";
import { useEffect, useState } from "react";
import SiteHeader, { getInitialTheme, type Theme } from "./SiteHeader";

type Locale="en"|"fa"; type Theme="light"|"dark";
const copy={
 en:{
  tag:"01 / Security",titleA:"SECURITY IS",titleB:"AN OPERATING PROPERTY.",body:"ONYX treats security as a property of the operational system: identity, authority, state, synchronization, auditability, and deployment controls must remain explicit as connectivity changes.",home:"Back to home",product:"Product model",contact:"Request a demo",language:"فارسی",light:"Light mode",dark:"Dark mode",
  principlesTag:"02 / Security model",principlesTitleA:"Protect the",principlesTitleB:"operational boundary.",principlesBody:"Security cannot be reduced to a perimeter around a central service. A local-first system must define what a node may know, change, synchronize, and execute—and how those actions become accountable.",
  principles:[["IDENTITY","Know the actor","Authentication and identity establish who or what is participating. Exact identity mechanisms depend on the deployment."],["AUTHORITY","Constrain action","Authorization determines what an actor or component may do. Connectivity should not silently expand authority."],["STATE","Protect information","Operational state needs appropriate confidentiality, integrity, and lifecycle controls at rest and in transit."],["SYNC","Control reconciliation","Synchronization is a security boundary: distributed changes require defined identity, conflict, authority, and verification rules."],["AUDIT","Preserve evidence","Important actions and state transitions should be attributable and inspectable according to the target environment."],["DEPLOYMENT","Match the environment","Network topology, secrets, storage, updates, isolation, and monitoring must be designed for the actual deployment context."]],
  threatTag:"03 / Threat model",threatTitleA:"Design around",threatTitleB:"failure and misuse.",threatBody:"The security model should account for both unavailable infrastructure and actions that are not authorized. These are design concerns, not claims that the platform automatically solves every threat.",
  threats:[["NETWORK LOSS","Availability","Connectivity can disappear without making local execution equivalent to unrestricted execution."],["STALE STATE","Integrity","Operators need visibility into the state they are acting against and how it was reconciled."],["UNAUTHORIZED ACTION","Authorization","A synchronized state must not be treated as permission to perform every possible action."],["CONFLICTING CHANGES","Consistency","Reconciliation needs deterministic, inspectable rules appropriate to the data and authority model."],["COMPROMISED NODE","Containment","Isolation, credentials, update policy, monitoring, and recovery depend on deployment architecture."]],
  controlsTag:"04 / Control domains",controlsTitleA:"Security controls",controlsTitleB:"follow the system boundary.",controlsBody:"The following domains provide the security checklist for an ONYX deployment. They are architectural concerns, not a certification statement.",
  controls:[["01","IDENTITY & ACCESS","Authentication, authorization, roles, service identities, credential lifecycle."],["02","DATA PROTECTION","Encryption requirements, key management, data classification, retention and deletion."],["03","SYNCHRONIZATION","Peer identity, transport protection, reconciliation rules, replay/conflict handling."],["04","AUDIT & OBSERVABILITY","Action attribution, security events, state transitions, monitoring and investigation."],["05","PLATFORM & SUPPLY CHAIN","Build provenance, dependency hygiene, signed/reproducible artifacts where required, update controls."],["06","DEPLOYMENT & RECOVERY","Isolation, secrets, backup/recovery, incident response, resilience and operational procedures."]],
  statusTag:"05 / Assurance boundary",statusTitleA:"What this page",statusTitleB:"does not claim.",statusBody:"Security requirements vary by deployment, threat model, jurisdiction, and assurance target. ONYX's public site should not imply a certification, compliance status, penetration-test result, or security guarantee unless supported by published evidence.",
  status:[["DOCUMENTED","Security architecture","Identity, authority, state, synchronization, auditability, and deployment are explicit security domains."],["ENVIRONMENT-DEPENDENT","Controls","Concrete mechanisms, configurations, retention, key management, and compliance requirements depend on deployment."],["EVIDENCE REQUIRED","Assurance claims","Certifications, audits, test results, compliance attestations, and customer security outcomes require separate evidence."]],
  futureTag:"06 / Future agent security",futureTitleA:"Agents inherit",futureTitleB:"the same boundaries.",futureBody:"A future Agentic AI / Plugin interface should not create a privileged side door. Agent actions should remain attributable, authorized, constrained by operational state, and verifiable.",
  future:["Observe only what the agent is authorized to access.","Propose actions without bypassing authorization.","Execute only through governed system interfaces.","Record agent identity, requested action, authorization, and result.","Verify resulting state before treating the operation as complete."],
  ctaTag:"07 / Continue",ctaTitleA:"Security belongs",ctaTitleB:"inside the architecture.",ctaBody:"Inspect the architecture model or discuss the security requirements of a concrete deployment.",architecture:"View architecture"
 },
 fa:{
  tag:"۰۱ / امنیت",titleA:"امنیت",titleB:"یک ویژگی عملیاتی است.",body:"در ONYX امنیت یک ویژگی از خود سامانه عملیاتی است: هویت، اختیار، وضعیت، همگام‌سازی، ممیزی و کنترل‌های استقرار باید با تغییر وضعیت اتصال همچنان صریح باقی بمانند.",home:"بازگشت به خانه",product:"مدل محصول",contact:"درخواست دمو",language:"فارسی",light:"حالت روشن",dark:"حالت تاریک",
  principlesTag:"۰۲ / مدل امنیتی",principlesTitleA:"از مرز",principlesTitleB:"عملیاتی محافظت کنید.",principlesBody:"امنیت را نمی‌توان فقط به یک پیرامون شبکه‌ای در اطراف سرویس مرکزی تقلیل داد. سامانه محلی‌محور باید مشخص کند هر گره چه چیزی را می‌تواند ببیند، تغییر دهد، همگام کند و اجرا کند و این اقدامات چگونه پاسخ‌گو می‌مانند.",
  principles:[["هویت","بازیگر را بشناسید","احراز هویت و هویت مشخص می‌کنند چه کسی یا چه چیزی مشارکت دارد. روش دقیق هویت به استقرار وابسته است."],["اختیار","عمل را محدود کنید","مجوز مشخص می‌کند بازیگر یا مؤلفه چه کاری می‌تواند انجام دهد. اتصال نباید به‌طور ضمنی اختیار را افزایش دهد."],["وضعیت","از اطلاعات محافظت کنید","وضعیت عملیاتی به کنترل‌های مناسب محرمانگی، تمامیت و چرخه عمر در حالت سکون و انتقال نیاز دارد."],["همگام‌سازی","تلفیق را کنترل کنید","همگام‌سازی یک مرز امنیتی است: تغییرات توزیع‌شده به قواعد مشخص هویت، تعارض، اختیار و راستی‌آزمایی نیاز دارند."],["ممیزی","شواهد را حفظ کنید","اقدامات و تغییرات مهم باید طبق محیط هدف قابل انتساب و بازرسی باشند."],["استقرار","با محیط منطبق شوید","توپولوژی شبکه، اسرار، ذخیره‌سازی، به‌روزرسانی، جداسازی و پایش باید برای محیط واقعی طراحی شوند."]],
  threatTag:"۰۳ / مدل تهدید",threatTitleA:"برای",threatTitleB:"شکست و سوءاستفاده طراحی کنید.",threatBody:"مدل امنیتی باید هم زیرساخت در دسترس نباشد و هم اقدام غیرمجاز را در نظر بگیرد. این‌ها ملاحظات طراحی‌اند، نه ادعای حل خودکار همه تهدیدها.",
  threats:[["قطع شبکه","دسترس‌پذیری","قطع اتصال نباید باعث شود اجرای محلی معادل اجرای بدون محدودیت تلقی شود."],["وضعیت قدیمی","تمامیت","اپراتور باید بداند بر اساس چه وضعیتی عمل می‌کند و آن وضعیت چگونه تلفیق شده است."],["اقدام غیرمجاز","مجوز","وضعیت همگام‌شده نباید به‌عنوان مجوز انجام هر اقدام ممکن تلقی شود."],["تغییرات متعارض","سازگاری","تلفیق باید قواعد مشخص، قابل بازرسی و متناسب با داده و مدل اختیار داشته باشد."],["گره به‌خطر‌افتاده","مهار","جداسازی، اعتبارنامه، به‌روزرسانی، پایش و بازیابی به معماری استقرار وابسته‌اند."]],
  controlsTag:"۰۴ / حوزه‌های کنترل",controlsTitleA:"کنترل‌های امنیتی",controlsTitleB:"مرز سامانه را دنبال می‌کنند.",controlsBody:"این حوزه‌ها چک‌لیست امنیتی یک استقرار ONYX را شکل می‌دهند و به‌معنای ادعای گواهی نیستند.",
  controls:[["۰۱","هویت و دسترسی","احراز هویت، مجوز، نقش‌ها، هویت سرویس‌ها و چرخه عمر اعتبارنامه."],["۰۲","حفاظت داده","رمزنگاری، مدیریت کلید، طبقه‌بندی داده، نگهداری و حذف."],["۰۳","همگام‌سازی","هویت همتا، حفاظت انتقال، قواعد تلفیق و کنترل بازپخش/تعارض."],["۰۴","ممیزی و مشاهده‌پذیری","انتساب اقدام، رویدادهای امنیتی، تغییر وضعیت، پایش و بررسی."],["۰۵","پلتفرم و زنجیره تأمین","منشأ ساخت، بهداشت وابستگی‌ها، صحت مصنوعات و کنترل به‌روزرسانی در صورت نیاز."],["۰۶","استقرار و بازیابی","جداسازی، اسرار، پشتیبان‌گیری، بازیابی، پاسخ به رخداد و رویه‌های عملیاتی."]],
  statusTag:"۰۵ / مرز تضمین",statusTitleA:"این صفحه چه چیزی",statusTitleB:"را ادعا نمی‌کند.",statusBody:"نیازهای امنیتی به استقرار، مدل تهدید، حوزه قضایی و هدف تضمین وابسته‌اند. سایت ONYX نباید بدون شواهد منتشرشده ادعای گواهی، انطباق، نتیجه تست نفوذ یا تضمین امنیتی داشته باشد.",
  status:[["مستند","معماری امنیت","هویت، اختیار، وضعیت، همگام‌سازی، ممیزی و استقرار به‌عنوان حوزه‌های امنیتی صریح هستند."],["وابسته به محیط","کنترل‌ها","مکانیزم‌های دقیق، پیکربندی، نگهداری، مدیریت کلید و انطباق به استقرار وابسته‌اند."],["نیازمند شواهد","ادعاهای تضمین","گواهی، ممیزی، نتایج آزمون، اظهارنامه انطباق و نتایج امنیتی مشتری نیازمند شواهد جداگانه‌اند."]],
  futureTag:"۰۶ / امنیت عامل‌ها",futureTitleA:"عامل‌ها همان",futureTitleB:"مرزها را به ارث می‌برند.",futureBody:"رابط آینده هوش مصنوعی عامل‌محور / افزونه نباید یک مسیر ممتاز و پنهان ایجاد کند. اقدامات عامل باید قابل انتساب، مجاز، محدود به وضعیت عملیاتی و قابل راستی‌آزمایی باشند.",
  future:["عامل فقط آنچه را مجاز است مشاهده کند.","اقدام را بدون دور زدن مجوز پیشنهاد کند.","فقط از رابط‌های کنترل‌شده برای اجرا استفاده کند.","هویت عامل، درخواست، مجوز و نتیجه ثبت شود.","پیش از کامل دانستن عملیات، وضعیت حاصل را راستی‌آزمایی کند."],
  ctaTag:"۰۷ / ادامه",ctaTitleA:"امنیت باید",ctaTitleB:"درون معماری باشد.",ctaBody:"مدل معماری را بررسی کنید یا الزامات امنیتی یک استقرار مشخص را با تیم مطرح کنید.",architecture:"مشاهده معماری"
 }
} as const;

export default function SecurityPage({locale}:{locale:Locale}){
 const [theme,setTheme]=useState<Theme>(()=>typeof window!=="undefined"&&window.localStorage.getItem("onyx-theme")==="dark"?"dark":"light");
 const rtl=locale==="fa",t=copy[locale]; const link=(p:string)=>p?`/${locale}/${p}/`:`/${locale}/`;
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.lang=locale;document.documentElement.dir=rtl?"rtl":"ltr";window.localStorage.setItem("onyx-theme",theme)},[theme,locale,rtl]);
 return <div className={`security-page security-page--${theme}`} dir={rtl?"rtl":"ltr"}>
  <SiteHeader locale={locale} theme={theme} onToggleTheme={() => setTheme((current) => current === "dark" ? "light" : "dark")} activePage="security" />
  <main>
   <section className="security-hero"><div className="security-hero__grid"/><div className="shell-content"><div className="security-kicker"><ShieldCheck size={15}/>{t.tag}</div><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p>{t.body}</p><div className="security-actions"><a className="security-button security-button--primary" href={link("architecture")}>{t.product}<ArrowRight size={15}/></a><a className="security-button" href={link("contact")}>{t.contact}</a></div><a className="security-home" href={link("")}><ArrowLeft size={15}/>{t.home}</a></div></section>
   <section className="security-section"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.principlesTag}</div><h2>{t.principlesTitleA}<br/><em>{t.principlesTitleB}</em></h2><p>{t.principlesBody}</p></div><div className="security-principles">{t.principles.map(([a,b,c],i)=><article key={a}><span>0{i+1}</span><b>{a}</b><h3>{b}</h3><p>{c}</p></article>)}</div></div></section>
   <section className="security-section security-section--threats"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.threatTag}</div><h2>{t.threatTitleA}<br/><em>{t.threatTitleB}</em></h2><p>{t.threatBody}</p></div><div className="security-threats">{t.threats.map(([a,b,c])=><article key={a}><b>{a}</b><span>{b}</span><p>{c}</p></article>)}</div></div></section>
   <section className="security-section"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.controlsTag}</div><h2>{t.controlsTitleA}<br/><em>{t.controlsTitleB}</em></h2><p>{t.controlsBody}</p></div><div className="security-controls">{t.controls.map(([n,a,b])=><article key={n}><span>{n}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
   <section className="security-section security-section--status"><div className="shell-content"><div className="security-two-col"><div><div className="security-kicker"><span/>{t.statusTag}</div><h2>{t.statusTitleA}<br/><em>{t.statusTitleB}</em></h2><p>{t.statusBody}</p></div><div className="security-status">{t.status.map(([a,b,c])=><article key={a}><b>{a}</b><div><h3>{b}</h3><p>{c}</p></div></article>)}</div></div></div></section>
   <section className="security-section security-section--future"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.futureTag}</div><h2>{t.futureTitleA}<br/><em>{t.futureTitleB}</em></h2><p>{t.futureBody}</p></div><div className="security-future">{t.future.map((x,i)=><div key={x}><span>0{i+1}</span><Check size={16}/><p>{x}</p></div>)}</div></div></section>
   <section className="security-final"><div className="shell-content"><div className="security-kicker"><span/>{t.ctaTag}</div><h2>{t.ctaTitleA}<br/><em>{t.ctaTitleB}</em></h2><p>{t.ctaBody}</p><div className="security-actions"><a className="security-button security-button--primary" href={link("architecture")}>{t.architecture}</a><a className="security-button" href={link("contact")}>{t.contact}</a></div></div></section>
  </main>
  <footer className="security-footer"><div className="shell-content"><img src={theme==="dark"?"/assets/onyx-horizontal-dark.svg":"/assets/onyx-horizontal-light.svg"} alt="ONYX"/><span>© {new Date().getFullYear()} ONYX · <a href="https://bound-method.github.io/" target="_blank" rel="noreferrer">BOUND Method</a></span></div></footer>
 </div>
}
