import { ArrowLeft, ArrowRight, Check, ChevronRight, Moon, ShieldCheck, Sun } from "lucide-react";
import { useEffect, useState } from "react";
import SiteHeader, { getInitialTheme } from "./SiteHeader";

type Locale="en"|"fa"; type Theme="light"|"dark";
const copy={
 en:{
  tag:"01 / Security",titleA:"SECURITY LIVES",titleB:"AT EVERY BOUNDARY.",body:"ONYX treats security as a property of the execution path: identity, authority, state, synchronization, evidence, and recovery. The repository contains concrete security mechanisms, while deployment-specific controls and assurance remain separate questions.",home:"Back to home",product:"Product model",contact:"Request a demo",language:"فارسی",light:"Light mode",dark:"Dark mode",
  principlesTag:"02 / Security model",principlesTitleA:"Identity → Authority",principlesTitleB:"→ State → Sync → Evidence → Recovery.",principlesBody:"These are the security boundaries of a distributed operational system. Each stage constrains the next; synchronization does not create authority, local state does not erase accountability, and recovery must preserve the evidence needed to understand what happened.",
  principles:[
   ["IDENTITY","Know the actor","Authentication establishes the principal, organization, user class, client class, or service participating in an operation. The repository documents Argon2id password hashing, signed authority/session-token infrastructure, revocation, organization-scoped identity, and client-type classification."],
   ["AUTHORITY","Constrain the action","Authorization determines whether that principal and client may perform the requested operation. ONYX separates user authority from client capability; a powerful user does not gain unrestricted mutation rights simply by using a different client."],
   ["STATE","Protect the operational record","Security applies to the state being read and changed: local operational state, server-side state, policies, approvals, files, and other domain records. Durable state must retain integrity while remaining subject to the deployment's confidentiality and lifecycle controls."],
   ["SYNCHRONIZATION","Reconcile without widening trust","Distributed replicas exchange changes under synchronization rules. Vector clocks, replica identity, operation batches, acknowledgements, conflict handling, and scoped relay tickets form boundaries around distributed change; synchronization itself is not a grant of authority."],
   ["EVIDENCE","Make actions attributable","Operational history and audit structures provide the evidence needed to reconstruct actions, decisions, state transitions, and verification. Auditability is part of the security model rather than a separate request-log afterthought."],
   ["RECOVERY","Restore without losing control","Recovery includes retry, replay/idempotency safeguards, synchronization after disruption, revocation, backup/restore, and deployment procedures. The exact recovery controls depend on the environment and must preserve authority and evidence."]
  ],
  threatTag:"03 / What ONYX protects",threatTitleA:"Protect the operation",threatTitleB:"at its actual boundaries.",threatBody:"The security target is not only a server perimeter. ONYX must protect identity and authority decisions, operational state, distributed changes, evidence, and recovery paths while recognizing that deployment controls remain part of the overall security boundary.",
  threats:[
   ["IDENTITY","Who is participating?","Protect credentials, sessions, signing material, organization identity, and client classification so an actor cannot simply impersonate a different operational principal."],
   ["AUTHORITY","Who may act?","Protect role, organization, delegation, approval, and client-capability boundaries. Authority must be evaluated at the operation boundary, not inferred from connectivity."],
   ["STATE","What may be changed?","Protect operational records and local replicas against unauthorized mutation, stale assumptions, and unsafe persistence choices."],
   ["SYNCHRONIZATION","What may cross replicas?","Protect transport and replica identity while keeping merge, conflict, acknowledgement, replay, and relay behavior inside explicit synchronization rules."],
   ["EVIDENCE","Can the action be reconstructed?","Protect audit integrity and operational history so important actions can be attributed and investigated according to the deployment's requirements."],
   ["RECOVERY","What happens after disruption?","Protect retry, replay, revocation, restoration, and re-entry into synchronization so recovery does not become an authorization bypass."]
  ],
  controlsTag:"04 / Security boundaries",controlsTitleA:"Controls follow",controlsTitleB:"the operational lifecycle.",controlsBody:"These controls are the concrete security domains to evaluate for an ONYX deployment. They are not a certification statement and do not replace deployment-specific threat modeling or assurance work.",
  controls:[
   ["01","AUTHENTICATION","Argon2id password hashing, signed session/authority-token infrastructure, organization-scoped identity, and token revocation are present in the security stack."],
   ["02","AUTHORIZATION","Capability checks, client-type boundaries, organization scope, lifecycle/authority epochs, and server-side command enforcement constrain execution."],
   ["03","TRANSPORT","Rustls-backed TLS dependencies, authenticated API paths, WebSocket event routes, and explicit CORS handling form the transport boundary."],
   ["04","INTEGRITY & AUDIT","Ed25519 signing infrastructure, audit application components, durable event history, and integrity-oriented verification support traceability."],
   ["05","SUPPLY CHAIN","SPDX SBOM generation, container signing with cosign, GPG-detached binary artifacts, and GitHub build attestations are part of the release model."],
   ["06","DEPLOYMENT & RECOVERY","Docker, Helm, Terraform, backup/recovery documentation, monitoring, and deployment runbooks form the operational security surface."]
  ],
   statusTag:"05 / Implementation status",statusTitleA:"Security mechanisms",statusTitleB:"have different maturity levels.",statusBody:"A mechanism in the repository is not the same thing as a deployed security outcome. This page therefore separates implementation evidence, deployment controls, and assurance evidence.",
  status:[
   ["IMPLEMENTED / DOCUMENTED","Identity & authority foundation","The repository documents Argon2id password hashing, signed authority/session-token infrastructure, revocation, organization-scoped identity, client-type capability enforcement, role/authority checks, and one-time Admin bootstrap controls."],
   ["IMPLEMENTED / DOCUMENTED","Distributed security controls","The current application manifest documents vector-clock synchronization, explicit conflict review, replica acknowledgement, durable operation batches, short-lived single-use scoped relay tickets, and audit/integrity structures."],
   ["IMPLEMENTATION-DEPENDENT","Data protection & recovery","Encryption configuration, key management, retention/deletion, backup strategy, incident response, isolation, monitoring, and recovery procedures must be established for the actual deployment."],
   ["ASSURANCE REQUIRED","Certifications & external evidence","Certifications, compliance attestations, penetration-test results, customer security outcomes, and other assurance claims require separate evidence. None are implied by this page."],
   ["IN DEVELOPMENT","Production hardening","Browser security, fail-closed CORS behavior, WebSocket authentication, supply-chain controls, and related production hardening remain explicit engineering work rather than assumed properties."]
  ],
  futureTag:"06 / Future agent security",futureTitleA:"Future agents",futureTitleB:"inherit the same model.",futureBody:"A future agent or plugin interface must not become a privileged side door. Agent operations should enter through the same identity, authority, state, synchronization, evidence, and recovery boundaries as human-initiated operations.",
  future:["Identify the agent and the principal or context under which it acts.","Evaluate authorization before allowing a mutation.","Constrain access to the operational state exposed to the agent.","Record the requested action, authorization context, result, and relevant evidence.","Apply synchronization, replay, conflict, and recovery rules exactly as for other governed operations."],
  ctaTag:"07 / Continue",ctaTitleA:"Security belongs",ctaTitleB:"inside the architecture.",ctaBody:"Inspect the architecture model or discuss the security requirements of a concrete deployment.",architecture:"View architecture"
 }, fa:{
  tag:"۰۱ / امنیت",titleA:"امنیت",titleB:"یک ویژگی عملیاتی است.",body:"در ONYX امنیت یک ویژگی از خود سامانه عملیاتی است: هویت، اختیار، وضعیت، همگام‌سازی، ممیزی و کنترل‌های استقرار باید با تغییر وضعیت اتصال همچنان صریح باقی بمانند.",home:"بازگشت به خانه",product:"مدل محصول",contact:"درخواست دمو",language:"فارسی",light:"حالت روشن",dark:"حالت تاریک",
  principlesTag:"۰۲ / مدل امنیتی",principlesTitleA:"از مرز",principlesTitleB:"عملیاتی محافظت کنید.",principlesBody:"امنیت را نمی‌توان فقط به یک پیرامون شبکه‌ای در اطراف سرویس مرکزی تقلیل داد. سامانه محلی‌محور باید مشخص کند هر گره چه چیزی را می‌تواند ببیند، تغییر دهد، همگام کند و اجرا کند و این اقدامات چگونه پاسخ‌گو می‌مانند.",
  principles:[["هویت","بازیگر را بشناسید","احراز هویت و هویت مشخص می‌کنند چه کسی یا چه چیزی مشارکت دارد. روش دقیق هویت به استقرار وابسته است."],["اختیار","عمل را محدود کنید","مجوز مشخص می‌کند بازیگر یا مؤلفه چه کاری می‌تواند انجام دهد. اتصال نباید به‌طور ضمنی اختیار را افزایش دهد."],["وضعیت","از اطلاعات محافظت کنید","وضعیت عملیاتی به کنترل‌های مناسب محرمانگی، تمامیت و چرخه عمر در حالت سکون و انتقال نیاز دارد."],["همگام‌سازی","تلفیق را کنترل کنید","همگام‌سازی یک مرز امنیتی است: تغییرات توزیع‌شده به قواعد مشخص هویت، تعارض، اختیار و راستی‌آزمایی نیاز دارند."],["ممیزی","شواهد را حفظ کنید","اقدامات و تغییرات مهم باید طبق محیط هدف قابل انتساب و بازرسی باشند."],["استقرار","با محیط منطبق شوید","توپولوژی شبکه، اسرار، ذخیره‌سازی، به‌روزرسانی، جداسازی و پایش باید برای محیط واقعی طراحی شوند."]],
  threatTag:"۰۳ / مدل تهدید",threatTitleA:"برای",threatTitleB:"شکست و سوءاستفاده طراحی کنید.",threatBody:"مدل امنیتی باید هم زیرساخت در دسترس نباشد و هم اقدام غیرمجاز را در نظر بگیرد. این‌ها ملاحظات طراحی‌اند، نه ادعای حل خودکار همه تهدیدها.",
  threats:[["قطع شبکه","دسترس‌پذیری","قطع اتصال نباید باعث شود اجرای محلی معادل اجرای بدون محدودیت تلقی شود."],["وضعیت قدیمی","تمامیت","اپراتور باید بداند بر اساس چه وضعیتی عمل می‌کند و آن وضعیت چگونه تلفیق شده است."],["اقدام غیرمجاز","مجوز","وضعیت همگام‌شده نباید به‌عنوان مجوز انجام هر اقدام ممکن تلقی شود."],["تغییرات متعارض","سازگاری","تلفیق باید قواعد مشخص، قابل بازرسی و متناسب با داده و مدل اختیار داشته باشد."],["گره به‌خطر‌افتاده","مهار","جداسازی، اعتبارنامه، به‌روزرسانی، پایش و بازیابی به معماری استقرار وابسته‌اند."]],
  controlsTag:"۰۴ / حوزه‌های کنترل",controlsTitleA:"کنترل‌های امنیتی",controlsTitleB:"مرز سامانه را دنبال می‌کنند.",controlsBody:"این حوزه‌ها چک‌لیست امنیتی یک استقرار ONYX را شکل می‌دهند و به‌معنای ادعای گواهی نیستند.",
  controls:[["۰۱","هویت و دسترسی","احراز هویت، مجوز، نقش‌ها، هویت سرویس‌ها و چرخه عمر اعتبارنامه."],["۰۲","حفاظت داده","رمزنگاری، مدیریت کلید، طبقه‌بندی داده، نگهداری و حذف."],["۰۳","همگام‌سازی","هویت همتا، حفاظت انتقال، قواعد تلفیق و کنترل بازپخش/تعارض."],["۰۴","ممیزی و مشاهده‌پذیری","انتساب اقدام، رویدادهای امنیتی، تغییر وضعیت، پایش و بررسی."],["۰۵","پلتفرم و زنجیره تأمین","منشأ ساخت، بهداشت وابستگی‌ها، صحت مصنوعات و کنترل به‌روزرسانی در صورت نیاز."],["۰۶","استقرار و بازیابی","جداسازی، اسرار، پشتیبان‌گیری، بازیابی، پاسخ به رخداد و رویه‌های عملیاتی."]],
  statusTag:"۰۵ / مرز تضمین",statusTitleA:"این صفحه چه چیزی",statusTitleB:"را ادعا نمی‌کند.",statusBody:"نیازهای امنیتی به استقرار، مدل تهدید، حوزه قضایی و هدف تضمین وابسته‌اند. سایت ONYX نباید بدون شواهد منتشرشده ادعای گواهی، انطباق، نتیجه تست نفوذ یا تضمین امنیتی داشته باشد.",
  status:[["مستند","معماری امنیت","هویت، اختیار، وضعیت، همگام‌سازی، ممیزی و استقرار به‌عنوان حوزه‌های امنیتی صریح هستند."],["وابسته به محیط","کنترل‌ها","مکانیزم‌های دقیق، پیکربندی، نگهداری، مدیریت کلید و انطباق به استقرار وابسته‌اند."],["نیازمند شواهد","ادعاهای تضمین","گواهی، ممیزی، نتایج آزمون، اظهارنامه انطباق و نتایج امنیتی مشتری نیازمند شواهد جداگانه‌اند."]],
  futureTag:"۰۶ / امنیت عامل‌ها",futureTitleA:"عامل‌ها همان",futureTitleB:"مرزها را به ارث می‌برند.",futureBody:"رابط آینده هوش مصنوعی عامل‌محور / افزونه نباید یک مسیر ممتاز و پنهان ایجاد کند. اقدامات عامل باید قابل انتساب، مجاز، محدود به وضعیت عملیاتی و قابل راستی‌آزمایی باشند.",
  future:["عامل فقط آنچه را مجاز است مشاهده کند.","اقدام را بدون دور زدن مجوز پیشنهاد کند.","فقط از رابط‌های کنترل‌شده برای اجرا استفاده کند.","هویت عامل، درخواست، مجوز و نتیجه ثبت شود.","پیش از کامل دانستن عملیات، وضعیت حاصل را راستی‌آزمایی کند."],
  ctaTag:"۰۷ / ادامه",ctaTitleA:"امنیت باید",ctaTitleB:"درون معماری باشد.",ctaBody:"مدل معماری را بررسی کنید یا الزامات امنیتی یک استقرار مشخص را با تیم مطرح کنید.",architecture:"مشاهده معماری"
 }
} as const;

export default function SecurityPage({locale}:{locale:Locale}){
 const [theme,setTheme]=useState<Theme>(()=>typeof window!=="undefined"&&window.localStorage.getItem("onyx-theme")==="dark"?"dark":"light");
 const rtl=locale==="fa",t=copy[locale]; const link=(p:string)=>p?`/${locale}/${p}/`:`/${locale}/`;
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.lang=locale;document.documentElement.dir=rtl?"rtl":"ltr";window.localStorage.setItem("onyx-theme",theme)},[theme,locale,rtl]);
 return <div className={`security-page security-page--${theme}`} dir={rtl?"rtl":"ltr"}>
  <SiteHeader locale={locale} theme={theme} onToggleTheme={() => setTheme((current) => current === "dark" ? "light" : "dark")} activePage="security" />
  <main>
   <section className="security-hero"><div className="security-hero__grid"/><div className="shell-content"><div className="security-kicker"><ShieldCheck size={15}/>{t.tag}</div><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p>{t.body}</p><div className="security-actions"><a className="security-button security-button--primary" href={link("architecture")}>{t.product}<ArrowRight size={15}/></a><a className="security-button" href={link("contact")}>{t.contact}</a></div><a className="security-home" href={link("")}><ArrowLeft size={15}/>{t.home}</a></div></section>
   <section className="security-section"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.principlesTag}</div><h2>{t.principlesTitleA}<br/><em>{t.principlesTitleB}</em></h2><p>{t.principlesBody}</p></div><div className="security-principles">{t.principles.map(([a,b,c],i)=><article key={a}><span>0{i+1}</span><b>{a}</b><h3>{b}</h3><p>{c}</p></article>)}</div></div></section>
   <section className="security-section security-section--threats"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.threatTag}</div><h2>{t.threatTitleA}<br/><em>{t.threatTitleB}</em></h2><p>{t.threatBody}</p></div><div className="security-threats">{t.threats.map(([a,b,c])=><article key={a}><b>{a}</b><span>{b}</span><p>{c}</p></article>)}</div></div></section>
   <section className="security-section"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.controlsTag}</div><h2>{t.controlsTitleA}<br/><em>{t.controlsTitleB}</em></h2><p>{t.controlsBody}</p></div><div className="security-controls">{t.controls.map(([n,a,b])=><article key={n}><span>{n}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
   <section className="security-section security-section--status"><div className="shell-content"><div className="security-two-col"><div><div className="security-kicker"><span/>{t.statusTag}</div><h2>{t.statusTitleA}<br/><em>{t.statusTitleB}</em></h2><p>{t.statusBody}</p></div><div className="security-status">{t.status.map(([a,b,c])=><article key={a}><b>{a}</b><div><h3>{b}</h3><p>{c}</p></div></article>)}</div></div></div></section>
   <section className="security-section security-section--future"><div className="shell-content"><div className="security-heading"><div className="security-kicker"><span/>{t.futureTag}</div><h2>{t.futureTitleA}<br/><em>{t.futureTitleB}</em></h2><p>{t.futureBody}</p></div><div className="security-future">{t.future.map((x,i)=><div key={x}><span>0{i+1}</span><Check size={16}/><p>{x}</p></div>)}</div></div></section>
   <section className="security-final"><div className="shell-content"><div className="security-kicker"><span/>{t.ctaTag}</div><h2>{t.ctaTitleA}<br/><em>{t.ctaTitleB}</em></h2><p>{t.ctaBody}</p><div className="security-actions"><a className="security-button security-button--primary" href={link("architecture")}>{t.architecture}</a><a className="security-button" href={link("contact")}>{t.contact}</a></div></div></section>
  </main>
  <footer className="security-footer"><div className="shell-content"><img src={theme==="dark"?"/assets/onyx-horizontal-dark.svg":"/assets/onyx-horizontal-light.svg"} alt="ONYX"/><span>© {new Date().getFullYear()} ONYX · <a href="https://bound-method.github.io/" target="_blank" rel="noreferrer">BOUND Method</a></span></div></footer>
 </div>
}
